version: "3.9"

services:
  node:
    build: .
    environment: 
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "5000:5000"
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data

volumes:
  db-data:

